services:
  - type: web
    name: setu-swasth
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: LLM_API_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: OTP_SECRET
        sync: false
